version: "3.9"

services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"

  chroma:
    image: chromadb/chroma
    ports:
      - 8080:8080

  fastapi:
    image: fastapi
    command: python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/app
