# version: "3"

# services:
#   web:
#     build:
#       #context: .
#       # dockerfile: dockerfile
#     volumes:
#       - .:/app
#     ports:
#       - 8000:8000
#     # command: bash -c "
#     #     django-admin startproject toyproject
#     #     && python ./toyproject/manage.py runserver 0.0.0.0:8000
#     #   "

version: "3.9" # Adjust the version if needed based on your Docker environment

services:
  # elasticsearch:
  #   image: elasticsearch:8.13.0
  #   environment:
  #     - discovery.type=single-node
  #   ports:
  #     - 9200:9200
  #   volumes:
  #     - elasticsearch-data:/var/lib/elasticsearch

  db:
    image: postgres:13.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - "./init/:/docker-entrypoint-initdb.d/"

  chroma:
    image: chromadb/chroma
    ports:
      - 8080:8080

  fastapi:
    image: fastapi
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - 8000:8000
    volumes:
      - ./app:/code/app
    # depends_on:
    #   - elasticsearch
  # Replace 'main:app' with the actual entrypoint in your Fast API application
